const commons=n=>`https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(n)}`;
const source=n=>`https://commons.wikimedia.org/wiki/File:${encodeURIComponent(n.replaceAll(' ','_'))}`;
const S=(id,name,date,tag,a,b,accent,desc,developments)=>({id,name,date,tag,a,b,accent,desc,developments});
const X=(id,sector,title,date,region,file,credit,intro,sections,timeline,facts,meanwhile,related,interactive='timeline')=>({id,sector,title,date,region,image:commons(file),source:source(file),credit,intro,sections,timeline,facts,meanwhile,related,interactive});
window.HISTORY_DATA={version:'1.1.0',sectors:[
S('prehistory','Prehistory','c. 300,000–3300 BCE','Origins','#d86b37','#25120d','#ffb36a','Human evolution, migration, art, adaptation, and the long transition from mobile lifeways toward settled communities.',['Homo sapiens emerges in Africa','Long-distance migrations','Symbolic art and ritual','Domestication and farming','Permanent settlements']),
S('bronze','Bronze Age','c. 3300–1200 BCE','Cities & bronze','#c97731','#24140c','#f0b46b','Cities, writing, palace economies, bronze metallurgy, monumental building, and long-distance exchange.',['Urban civilizations','Writing and administration','Bronze metallurgy','Monumental architecture','Interregional trade']),
S('iron','Iron Age','c. 1200–500 BCE','Empires & iron','#728c8f','#142126','#a6d6d8','Iron technologies, resilient trade networks, new imperial systems, and expanding political and religious traditions.',['Ironworking spreads','Neo-Assyrian power','Phoenician networks','Israel and Judah','Achaemenid expansion']),
S('classical','Classical','c. 500 BCE–500 CE','Empires & ideas','#5e79c9','#12182d','#9fb5ff','Mediterranean, South Asian, Central Asian, and East Asian empires linked by war, exchange, law, philosophy, and religion.',['Greek and Hellenistic worlds','Roman Mediterranean','Mauryan and Kushan networks','Qin and Han China','Long-distance exchange']),
S('medieval','Medieval','c. 500–1500 CE','Connected worlds','#b94364','#260f1a','#ff8daa','Byzantium, Islamic civilizations, African kingdoms, Asian dynasties, steppe empires, and intensifying global exchange.',['Byzantine continuity','Islamic expansion','Indian Ocean commerce','Viking and steppe mobility','Mongol Eurasia']),
S('early-modern','Early Modern','c. 1500–1800 CE','Oceanic worlds','#1ea39b','#081f20','#6ee8d9','Print, gunpowder empires, oceanic expansion, ecological exchange, scientific change, and political revolution.',['Print revolution','Oceanic empires','Columbian Exchange','Gunpowder states','Scientific revolution']),
S('industrial','Industrial','c. 1760–1914 CE','Steam & industry','#d09a3c','#282017','#ffd079','Fossil energy, factories, railways, electricity, mass cities, imperial expansion, and social transformation.',['Mechanized textiles','Steam power','Railway networks','Urbanization','Electric and chemical industries']),
S('world-wars','World Wars','1914–1945 CE','Total war','#b94f35','#1f100d','#ff9d75','Global war, revolution, fascism, genocide, mass mobilization, and the destruction of older international orders.',['World War I','Russian Revolution','Interwar crisis','World War II','Holocaust']),
S('modern','Modern Age','1945–present','Global systems','#397ccc','#0b1727','#73bdff','Cold War, decolonization, globalization, digital networks, social movements, and a changing international system.',['Cold War rivalry','Decolonization','Nuclear age','Global institutions','Digital globalization']),
S('science','Science & Technology','Across all eras','Special sector','#8f4fe0','#180d28','#c99cff','A cross-era gallery of inventions, discoveries, machines, information systems, and the institutions that made them possible.',['Print and knowledge','Steam and energy','Electric systems','Electronic computing','Networked information']),
S('space','Space Exploration','20th century–present','Special sector','#3150bc','#050918','#7ea2ff','Rockets, satellites, human spaceflight, planetary science, orbital laboratories, and exploration beyond Earth.',['Early rocketry','Space Race','Lunar exploration','Outer-planet missions','Orbital laboratories'])
],exhibits:[
X('human-migration','prehistory','Humanity on the Move','c. 70,000–15,000 years ago','Africa → the world','Göbeklitepe 2015-27.jpg','Wikimedia Commons','The history of Homo sapiens is inseparable from movement. Populations expanded within Africa and beyond it in repeated waves, adapting to deserts, coasts, grasslands, forests, cold steppe, and eventually the far edges of the inhabited world.',[
['Origins in Africa','Homo sapiens evolved in Africa, where genetic and archaeological evidence points to deep population structure rather than a single tiny birthplace. Long before major movements beyond Africa, human groups were already exchanging genes, technologies, and cultural practices across large distances.'],
['Across Eurasia and Sahul','Dispersals into Southwest Asia were followed by wider settlement across Eurasia. Modern humans encountered and interbred with Neanderthals and Denisovans. Reaching Sahul, the Ice Age landmass joining Australia and New Guinea, also required water crossings and demonstrates sophisticated planning.'],
['Into the Americas','People reached the Americas by at least the late Pleistocene. Scholars continue to debate precise routes and dates, but evidence shows that settlement was not a single march along one line. Coastal and interior pathways, shifting ice sheets, and rapidly changing environments all mattered.'],
['A connected human past','Migration did not end once continents were settled. Foragers, pastoralists, farmers, merchants, conquerors, refugees, and explorers continued to reshape populations. The map of humanity is a history of repeated movement, contact, mixture, and adaptation.']],[['c. 300,000 years ago','Early Homo sapiens in Africa'],['c. 70,000–50,000 years ago','Major dispersals beyond Africa'],['by c. 50,000 years ago','Humans established in Sahul'],['by c. 15,000 years ago','People established in the Americas']],[['Core idea','Many migrations, not one'],['Evidence','Archaeology + genetics'],['Key encounter','Neanderthals & Denisovans'],['Scale','Tens of millennia']],['Neanderthal populations persisted across parts of Eurasia.','Ice Age climates repeatedly altered coastlines and migration corridors.','Human communities were already producing symbolic objects and complex technologies.'],['neolithic-revolution','cave-art'], 'migration'),
X('neolithic-revolution','prehistory','The Neolithic Revolution','c. 10,000–3000 BCE','Multiple regions','Çatalhöyük overview.jpg','Verity Cridland · Wikimedia Commons','Farming was not invented once and simply copied everywhere. Different communities domesticated plants and animals in several regions, producing new settlements, diets, labor systems, inequalities, and relationships with landscapes.',[
['Many centers of domestication','Southwest Asia saw early cultivation of wheat and barley and management of sheep and goats, while other centers developed around rice and millet in East Asia, tubers in New Guinea, African crops, and maize and other domesticates in the Americas.'],
['Village life','Permanent or semi-permanent settlement changed architecture, storage, property, disease exposure, household organization, and population density. Places such as Çatalhöyük reveal dense communities whose inhabitants built, rebuilt, decorated, and buried within domestic spaces.'],
['Costs and transformations','Agriculture could support larger populations, but it often narrowed diets, intensified labor, and increased exposure to infectious disease. Surplus could support specialists and elites, yet the path from farming to hierarchy differed greatly by region.']],[['c. 10,000 BCE','Early cultivation intensifies in Southwest Asia'],['c. 9000–7000 BCE','Domesticated plants and animals become central in some communities'],['c. 7400 BCE','Çatalhöyük settlement develops'],['later millennia','Independent agricultural traditions expand in several world regions']],[['Change','Foraging → mixed farming systems'],['Result','Denser settlement'],['Not universal','Many societies remained mobile'],['Long effect','Population growth']],['Jericho was developing in Southwest Asia.','Different domestication processes were unfolding in East Asia.','In many regions, hunting and gathering remained highly successful.'],['human-migration','mesopotamia'],'compare'),
X('cave-art','prehistory','Cave Art & the Painted World','c. 40,000–12,000 years ago','Europe and beyond','Lascaux painting.jpg','Wikimedia Commons','Painted caves preserve only a fraction of prehistoric visual culture, but they demonstrate that Ice Age people created complex images, selected meaningful spaces, and transmitted symbolic traditions over generations.',[
['Images in deep places','Sites such as Chauvet and Lascaux contain animals, signs, hand marks, and rare human forms. Some works were placed far from cave entrances, implying deliberate movement through dark spaces using lamps and torches.'],
['Technique and observation','Artists used mineral pigments, charcoal, engraving, stenciling, and the natural contours of rock. Animal anatomy and movement were sometimes rendered with remarkable economy and precision.'],
['Meaning without certainty','Interpretations have ranged from hunting magic to shamanic experience, storytelling, memory, teaching, or social marking. Because no written explanation survives, responsible interpretation distinguishes evidence from speculation.']],[['c. 40,000 years ago','Some of the earliest known figurative cave traditions'],['c. 36,000 years ago','Chauvet imagery'],['c. 17,000 years ago','Lascaux paintings'],['1940','Lascaux discovered by modern visitors']],[['Medium','Mineral pigment & charcoal'],['Subjects','Animals, signs, hands'],['Challenge','Meaning remains debated'],['Environment','Often deep cave spaces']],['People were adapting to severe Ice Age environments.','Portable carvings and decorated objects circulated beyond caves.','Human populations remained mobile across much of Eurasia.'],['human-migration','neolithic-revolution'],'gallery'),
X('ancient-egypt','bronze','Ancient Egypt','c. 3100–30 BCE','Nile Valley','Great Pyramid (Pyramid of Cheops Khufu), Giza, GG, EGY (47902782131).jpg','Wikimedia Commons','Along the Nile, political institutions connected agriculture, royal power, writing, religion, craft production, and monumental architecture for more than three millennia.',[
['The Nile and the state','Seasonal Nile flooding and irrigation supported dense agriculture, while river transport connected Upper and Lower Egypt. Officials assessed land, collected resources, organized labor, and maintained written administration. Geography supported unity, but Egyptian history also included long periods of political fragmentation.'],
['Kingship and monuments','Pharaohs were political rulers embedded in a sacred order. Old Kingdom pyramid complexes at Giza required quarrying, transport, food supply, skilled crafts, and coordinated labor on a huge scale. Evidence does not support the old popular image of the pyramids being built primarily by masses of enslaved workers.'],
['Writing, religion, and daily life','Hieroglyphic and cursive scripts recorded ritual, administration, literature, and personal concerns. Temples linked gods, landholding, wealth, and state power. Most Egyptians, however, experienced history through farming, family, craft, taxation, local worship, and obligations to authorities.'],
['Change across millennia','Egyptian society survived invasions and foreign dynasties while continuously changing. Hyksos rulers, Nubian pharaohs, Assyrians, Persians, Macedonians, and Romans all became part of its long political history.']],[['c. 3100 BCE','Political unification associated with early dynasties'],['c. 26th century BCE','Great Pyramid built at Giza'],['c. 1550–1070 BCE','New Kingdom imperial period'],['30 BCE','Ptolemaic kingdom ends; Egypt becomes Roman province']],[['River','Nile'],['Writing','Hieroglyphic + cursive scripts'],['Monument','Great Pyramid'],['Longevity','More than 3,000 years']],['Sumerian city-states flourished in Mesopotamia.','Trade connected the eastern Mediterranean, Red Sea, and Near East.','Bronze technology linked distant mining and exchange zones.'],['mesopotamia','bronze-age-collapse'],'timeline'),
X('mesopotamia','bronze','Mesopotamia & the First Cities','c. 3500–2000 BCE','Tigris–Euphrates','Standard of Ur - War.jpg','Wikimedia Commons · public-domain artwork','Southern Mesopotamia became one of the earliest regions where urban life, writing, institutions, and long-distance exchange reached a transformative scale.',[
['Cities on an engineered landscape','Uruk, Ur, Lagash, and other cities relied on irrigation systems that required coordination but also generated conflict over land and water. Temples, households, workshops, and governing institutions concentrated people and resources.'],
['Writing for administration—and more','Cuneiform developed from accounting practices and expanded into legal, literary, scholarly, and diplomatic uses. Writing did not make Mesopotamia the first complex society, but it left an unusually detailed record of institutions and ideas.'],
['Networks and rivalry','Mesopotamian cities traded for timber, stone, metals, and luxury materials unavailable on the alluvial plain. Political power shifted among cities and later territorial states, showing that early urbanization was dynamic rather than a single stable civilization.']],[['c. 3500 BCE','Uruk urban growth'],['late 4th millennium BCE','Early writing systems'],['c. 2600 BCE','Royal Cemetery of Ur era'],['c. 2334 BCE','Akkadian imperial expansion begins']],[['Landscape','Tigris & Euphrates'],['Script','Cuneiform'],['Urban center','Uruk'],['Need','Long-distance raw materials']],['Egyptian state formation was also underway.','Indus communities were developing toward large urban centers.','Trade crossed the Persian Gulf and Iranian plateau.'],['ancient-egypt','bronze-age-collapse','printing-press'],'network'),
X('bronze-age-collapse','bronze','The Bronze Age Collapse','c. 1200 BCE','Eastern Mediterranean','Medinet Habu Ramses III.jpg','Olaf Tausch · Wikimedia Commons · CC BY 3.0','Around 1200 BCE, several eastern Mediterranean palace systems fractured. The upheaval was real, but historians resist reducing it to a single invasion or one mysterious people.',[
['A system under pressure','Late Bronze Age courts depended on interlocking diplomacy, tribute, trade, specialized production, and political legitimacy. Disruption in one region could affect access to metals, grain, shipping, and elite goods elsewhere.'],
['War, migration, climate, revolt','Texts and archaeology point to warfare, population movement, destroyed settlements, political rebellion, and environmental stress. The “Sea Peoples” appear in Egyptian records, but they were part of a wider crisis rather than a complete explanation.'],
['Collapse and continuity','Mycenaean palaces and the Hittite imperial system disappeared, while Egypt survived in weakened form. Cyprus, the Levant, and other regions experienced varied outcomes. New communities and political forms emerged from the disruption.']],[['c. 1250–1200 BCE','Stress intensifies in several palace systems'],['c. 1200 BCE','Destructions and political breakdown across parts of the region'],['c. 1177 BCE','Ramesses III records conflict with groups called Sea Peoples'],['after 1150 BCE','New Iron Age political landscapes emerge']],[['Cause','Multiple interacting pressures'],['Common mistake','Single-cause invasion story'],['Major loss','Mycenaean & Hittite palace systems'],['Continuity','Many communities persisted']],['Assyria survived and later expanded.','Phoenician city networks developed in the Levant.','Ironworking became more widespread over subsequent centuries.'],['mesopotamia','persian-empire'],'timeline'),
X('persian-empire','iron','The Persian Empire','c. 550–330 BCE','West & Central Asia','Behistun relief.jpg','Patrick C / Pentocelo · Wikimedia Commons · CC BY-SA 2.0','The Achaemenid Empire governed an enormous and diverse territory through royal authority, provincial administration, roads, tribute, diplomacy, and negotiated local arrangements.',[
['From Cyrus to an empire','Cyrus II conquered Median, Lydian, and Babylonian territories, while later rulers extended Persian control from the Indus region to Egypt and the Aegean frontier. The empire integrated older states rather than erasing them.'],
['Administration at scale','Satrapies, royal inspectors, road systems, standardized practices, garrisons, and local elites helped govern distance. Aramaic became an important administrative language, while many local languages, laws, religions, and institutions continued.'],
['Royal ideology and resistance','Monuments such as Behistun presented the king as defender of order. Greek–Persian warfare became famous in later Western traditions, but those conflicts were only one frontier of a much larger imperial system.']],[['c. 550 BCE','Cyrus defeats the Median king'],['539 BCE','Babylon conquered'],['c. 500 BCE','Royal Road and imperial networks connect provinces'],['330 BCE','Achaemenid monarchy falls to Alexander']],[['Founder','Cyrus II'],['Royal center','Multiple capitals'],['Administration','Satrapies'],['Scale','Three continents']],['Greek city-states contested Persian power in the Aegean.','South Asian states developed east of the empire.','Trade moved across Central Asian and Near Eastern corridors.'],['alexander-the-great','mesopotamia'],'expansion'),
X('roman-empire','classical','The Roman Empire','27 BCE–476 CE in the West','Mediterranean world','Colosseum-Rom.jpg','Wikimedia Commons','Rome transformed a republican Mediterranean power into an imperial system of armies, taxes, roads, ports, cities, law, citizenship, and cultural exchange.',[
['Augustus and imperial rule','After civil wars destroyed the old republican balance, Augustus concentrated military and political authority while preserving republican titles. Later emperors relied on armies, provincial governors, court networks, taxation, patronage, and local elites.'],
['A connected Mediterranean','Sea lanes and roads moved grain, wine, oil, ceramics, metals, soldiers, officials, enslaved people, and ideas. Cities displayed baths, aqueducts, arenas, temples, forums, and apartment housing, but rural agriculture still supported most of the population.'],
['Citizenship, slavery, and inequality','Roman law and citizenship expanded over time, culminating in a broad grant of citizenship to free inhabitants of the empire in 212 CE. At the same time, Roman prosperity depended heavily on unequal landholding and slavery.'],
['Transformation, not disappearance','Political crises, civil wars, external pressures, fiscal strain, and shifting military structures transformed the empire. Western imperial government ended in the fifth century, while the eastern Roman state—later called Byzantine—continued for centuries.']],[['27 BCE','Octavian receives title Augustus'],['117 CE','Empire reaches greatest territorial extent under Trajan'],['212 CE','Constitutio Antoniniana broadens citizenship'],['476 CE','Traditional date for end of western imperial government']],[['First emperor','Augustus'],['Major language zones','Latin & Greek'],['Infrastructure','Roads, ports, aqueducts'],['Eastern continuation','Byzantine Empire']],['Han China ruled a vast East Asian empire.','Kushan rulers linked Central and South Asian trade routes.','Mesoamerican cities and states developed independently across the Atlantic.'],['han-china','byzantine-empire','alexander-the-great'],'expansion'),
X('alexander-the-great','classical','Alexander the Great','356–323 BCE','Macedon → Asia','Alexander the Great mosaic.jpg','Wikimedia Commons','Alexander III of Macedon destroyed the Achaemenid monarchy in a decade of campaigns, but the political and cultural world that followed was built by many peoples and successor states—not by one conqueror alone.',[
['Macedonian inheritance','Philip II had already transformed Macedon’s army and political position. Alexander inherited that system and crossed into Asia in 334 BCE, combining disciplined infantry, mobile cavalry, siegecraft, logistics, and personal command.'],
['Conquest and adaptation','Victories at Issus and Gaugamela opened the Persian imperial core. Alexander adopted some Achaemenid practices, founded or refounded cities, married into regional elites, and pressed east into Central and South Asia.'],
['An empire without succession','Alexander died in Babylon in 323 BCE without a stable adult heir. His commanders fought for decades, creating Hellenistic kingdoms whose courts mixed Greek and Macedonian institutions with older local traditions.']],[['356 BCE','Born at Pella'],['334 BCE','Crosses into Asia'],['331 BCE','Victory at Gaugamela'],['323 BCE','Dies in Babylon']],[['Father','Philip II'],['Key battle','Gaugamela'],['Extent','Egypt to South Asia'],['Aftermath','Hellenistic kingdoms']],['The Roman Republic was expanding in Italy.','Mauryan power soon rose in South Asia.','Chinese states fought during the late Warring States period.'],['persian-empire','roman-empire','han-china'],'expansion'),
X('han-china','classical','Han China','206 BCE–220 CE','East Asia','Mawangdui silk banner from tomb no1.jpg','Wikimedia Commons','The Han dynasty consolidated imperial institutions, expanded frontiers, developed state learning, and anchored exchange networks that connected East Asia to Central Asia and beyond.',[
['Building an imperial state','Han rulers inherited many Qin institutions but adjusted their severity. Commanderies, local elites, taxation, conscription, law, and an expanding bureaucracy supported a state governing tens of millions of people.'],
['Frontiers and exchange','Conflict with the Xiongnu pushed Han diplomacy and military activity into Central Asia. Goods moved through chains of merchants and states later described collectively as the Silk Roads; few travelers crossed the entire distance from China to Rome.'],
['Court, scholarship, and society','Confucian learning gained stronger official status, though governance also drew on legalist practices and practical administration. Rich tombs such as Mawangdui reveal medicine, cosmology, textiles, food, and elite life alongside a much larger agrarian society.']],[['206 BCE','Han dynasty established'],['141–87 BCE','Reign of Emperor Wu'],['1st century BCE','Stronger Central Asian connections'],['220 CE','Han dynasty ends']],[['Capital centers','Chang’an & Luoyang'],['Frontier rival','Xiongnu'],['Economy','Agrarian taxes + trade'],['Legacy','Durable imperial model']],['Rome was expanding around the Mediterranean.','Kushan power connected parts of Central and South Asia.','Indian Ocean trade linked East Africa, Arabia, India, and Southeast Asia.'],['roman-empire','alexander-the-great'],'network'),
X('mongol-empire','medieval','The Mongol Empire','1206–14th century','Eurasia','Mongol Empire at its extent.png','Wikimedia Commons','Mongol armies created the largest contiguous land empire in history, bringing destruction on an immense scale while also restructuring political and commercial connections across Eurasia.',[
['Temüjin becomes Chinggis Khan','In 1206, Temüjin was proclaimed Chinggis Khan after defeating rivals and building a new political coalition. Units organized across older tribal lines, strict discipline, intelligence, mounted mobility, and flexible tactics supported rapid campaigns.'],
['Conquest across Eurasia','Mongol and successor armies conquered northern China, Central Asia, Iran, Rus’ principalities, and much of the Middle East. Cities that resisted could face catastrophic violence; surrender sometimes brought negotiated survival.'],
['Pax Mongolica?','The phrase describes increased security and movement across some routes under Mongol rule, but it should not obscure warfare and coercion. Merchants, diplomats, artisans, technologies, and diseases traveled through an interconnected imperial world.'],
['Khanates and legacies','The unified empire fragmented into major khanates, including the Yuan, Ilkhanate, Golden Horde, and Chagatai realm. These states adopted local institutions while retaining Mongol political traditions.']],[['1206','Temüjin proclaimed Chinggis Khan'],['1219','Campaign against Khwarazm begins'],['1258','Baghdad captured by Hülegü'],['1271','Khubilai proclaims Yuan dynasty']],[['Founder','Chinggis Khan'],['Strength','Mobility + organization'],['System','Multiple successor khanates'],['Effect','Eurasian integration and devastation']],['Song China faced growing Mongol pressure.','Mali rose in West Africa.','Mediterranean merchant networks connected Europe, North Africa, and the Middle East.'],['black-death','byzantine-empire'],'expansion'),
X('byzantine-empire','medieval','The Byzantine Empire','330–1453 CE','Eastern Mediterranean','Hagia Sophia Mars 2013.jpg','Arild Vågen · Wikimedia Commons','The state modern historians call Byzantine was the eastern Roman Empire: a Christian, Greek-speaking imperial society that preserved Roman political identity while changing profoundly across eleven centuries.',[
['Roman continuity','Constantinople became an imperial capital in the fourth century. Its rulers called themselves Romans, maintained Roman law and imperial institutions, and governed territories that at times stretched across the Mediterranean.'],
['Justinian and transformation','Emperor Justinian sponsored the codification of Roman law and the construction of Hagia Sophia while his armies reconquered parts of the western Mediterranean. Plague, war, and fiscal strain made many gains temporary.'],
['A changing medieval empire','After Arab conquests transformed the seventh-century Mediterranean, the empire reorganized around Anatolia and the Balkans. Orthodox Christianity, Greek language, diplomacy, trade, and military adaptation shaped later centuries until Ottoman conquest in 1453.']],[['330','Constantinople dedicated as imperial capital'],['537','Hagia Sophia completed'],['1204','Fourth Crusade captures Constantinople'],['1453','Ottoman conquest of Constantinople']],[['Identity','Roman'],['Capital','Constantinople'],['Landmark','Hagia Sophia'],['End','1453']],['Sasanian Persia was a major rival before the Arab conquests.','Islamic caliphates transformed the eastern Mediterranean.','Western European kingdoms developed from post-Roman political worlds.'],['roman-empire','black-death'],'timeline'),
X('black-death','medieval','The Black Death','1346–1353','Eurasia & North Africa','Diffusion de la peste noire 1347 1351.svg','FlyingPC · Wikimedia Commons','A pandemic of plague killed a staggering share of populations across much of Eurasia and North Africa, reshaping labor, belief, politics, family life, and economic relations.',[
['A disease moving through networks','The bacterium Yersinia pestis circulated in animal reservoirs and moved along trade and military routes. The pandemic reached Black Sea and Mediterranean ports before spreading through densely connected towns and countryside.'],
['Mortality and disruption','Death rates varied dramatically by region, but many communities lost huge fractions of their populations. Households collapsed, clergy and officials died, markets were disrupted, and communities searched for explanations with limited medical knowledge.'],
['After the first wave','Plague returned repeatedly for centuries. Labor scarcity could strengthen some workers’ bargaining power, while authorities attempted wage controls and other interventions. Persecution also intensified, including horrific attacks on Jewish communities falsely blamed for the disease.']],[['1346','Major outbreaks around western Eurasia'],['1347','Plague reaches Mediterranean ports'],['1348–1350','Large parts of Europe and North Africa affected'],['later centuries','Recurring plague outbreaks']],[['Pathogen','Yersinia pestis'],['Route','Trade + movement'],['Impact','Mass mortality'],['Aftermath','Long demographic recovery']],['Mongol successor states controlled major trade corridors.','The Mali Empire remained a major West African power.','The Yuan dynasty was nearing its final decades in China.'],['mongol-empire','byzantine-empire'],'map'),
X('renaissance','early-modern','The Renaissance','c. 1300–1600','Europe','Mona Lisa, by Leonardo da Vinci, from C2RMF retouched.jpg','C2RMF / Wikimedia Commons','The Renaissance was not a sudden rebirth after a “dark” millennium. It was a set of cultural movements shaped by urban wealth, classical learning, patronage, artistic experiment, printing, and contacts across the Mediterranean and Europe.',[
['Humanism and texts','Scholars studied Greek and Latin works, developed new philological methods, and sought manuscripts across Europe and the eastern Mediterranean. Byzantine scholars and Arabic intellectual traditions were important parts of the transmission and interpretation of ancient knowledge.'],
['Art, craft, and patronage','Perspective, anatomy, oil painting, monumental sculpture, and architectural study became sites of intense experimentation. Courts, republics, churches, confraternities, and wealthy households competed as patrons.'],
['A wider context','Italian centers were influential, but Renaissance movements took distinctive forms in northern Europe and elsewhere. Printing accelerated circulation, while Atlantic expansion and colonial violence soon connected European cultural change to much larger global transformations.']],[['14th century','Italian humanist networks expand'],['c. 1450','Movable-type printing grows in Europe'],['late 15th century','High Renaissance artistic experimentation'],['16th century','Renaissance forms spread and diversify']],[['Concept','Multiple renaissances'],['Key force','Patronage'],['Method','Humanist philology'],['Technology','Printing']],['Ottoman power linked the eastern Mediterranean.','Ming China was a major commercial and cultural center.','West African and Indian Ocean networks connected distant markets.'],['printing-press','age-of-exploration'],'gallery'),
X('age-of-exploration','early-modern','The Age of Exploration','15th–17th centuries','Atlantic & Indian Oceans','Cantino planisphere (1502).jpg','Wikimedia Commons · public-domain map','Oceanic voyages linked the Atlantic, Indian, and Pacific worlds more tightly than before, producing new knowledge and exchange alongside conquest, enslavement, epidemic disease, and colonial dispossession.',[
['Navigation and maritime systems','Iberian mariners combined ship design, astronomical navigation, cartography, commercial finance, and knowledge drawn from Mediterranean and Atlantic traditions. They entered ocean systems where African, Arab, Indian, Malay, and Chinese sailors already had deep expertise.'],
['The Columbian Exchange','After 1492, plants, animals, pathogens, people, and commodities moved between hemispheres at unprecedented scale. American crops transformed diets elsewhere, while Old World diseases caused catastrophic mortality among Indigenous populations.'],
['Empire and resistance','Portuguese and Spanish expansion was followed by Dutch, English, French, and other imperial projects. Indigenous states negotiated, resisted, adapted, and survived; the Atlantic slave trade forcibly transported millions of Africans and became central to colonial economies.']],[['1488','Bartolomeu Dias rounds southern Africa'],['1492','Columbus reaches the Caribbean'],['1498','Vasco da Gama reaches India by sea from Europe'],['1519–1522','Magellan–Elcano expedition completes first circumnavigation']],[['Key change','Sustained oceanic links'],['Dark legacy','Conquest + slavery'],['Ecology','Columbian Exchange'],['Mapmaking','Rapidly changing world knowledge']],['Ming China participated in enormous regional trade.','Ottoman and Safavid states dominated key overland and maritime corridors.','African kingdoms engaged Atlantic trade on varied terms.'],['renaissance','decolonization'],'map'),
X('industrial-revolution','industrial','The Industrial Revolution','c. 1760–19th century','Britain → world','Spinning jenny.jpg','Wikimedia Commons','Industrialization reorganized energy, production, transport, labor, cities, and imperial power. It was not a single invention but a reinforcing system of machines, fossil fuel, capital, skills, institutions, and global resources.',[
['Textiles, coal, and steam','Mechanized spinning and weaving increased textile output while coal supplied concentrated energy. Improved steam engines pumped mines and later powered factories, ships, and locomotives.'],
['Factories and labor','Production increasingly moved into workplaces where owners controlled machinery, schedules, and discipline. Men, women, and children worked under difficult conditions; industrial conflict helped generate unions, reform movements, and new political ideologies.'],
['A global industrial system','Britain’s industrial growth depended partly on global trade, colonial markets, raw materials, finance, and Atlantic slavery’s legacies. Industrialization later spread unevenly to continental Europe, North America, Japan, and other regions.'],
['Cities and environments','Industrial cities grew rapidly, often faster than sanitation and housing. Smoke, contaminated water, crowding, and workplace hazards accompanied rising production, eventually spurring infrastructure and public-health reforms.']],[['1760s','Mechanized textile innovations accelerate'],['1770s–1780s','Watt steam engines spread'],['1825','Stockton and Darlington Railway opens'],['19th century','Industrialization spreads unevenly worldwide']],[['Early center','Britain'],['Energy','Coal + steam'],['Workplace','Factory system'],['Result','Mass urbanization']],['Atlantic revolutions reshaped politics.','European empires expanded their global reach.','Qing China remained one of the world’s largest economies.'],['steam-engine','age-of-railroads','world-war-i'],'machine'),
X('age-of-railroads','industrial','The Age of Railroads','1820s–early 20th century','Global','Locomotion No 1.jpg','Neil T · Wikimedia Commons · CC BY-SA 2.0','Railways compressed distance by combining steam power, iron, capital, standardized schedules, and massive infrastructure. They transformed markets and mobility while also serving empire, extraction, war, and settler expansion.',[
['A new transport system','Early public railways showed that locomotives could move heavy freight and passengers reliably. Tracks, bridges, tunnels, stations, repair shops, signaling, and timetables created an entire technological system.'],
['Time and markets','Railways linked farms, mines, factories, ports, and cities. They encouraged standardized time, reduced transport costs, increased migration, and changed where businesses and settlements could thrive.'],
['Power over land','Rail construction frequently depended on state backing, land seizure, coerced labor, or colonial authority. In North America and other settler societies, railways accelerated Indigenous dispossession; in empires they enabled extraction and troop movement.']],[['1825','Stockton and Darlington Railway'],['1830','Liverpool and Manchester Railway'],['1869','First U.S. transcontinental railroad completed'],['late 19th century','Large rail networks spread across Europe, Asia, Africa, and the Americas']],[['Engine','Steam locomotive'],['Effect','Distance compressed'],['Institution','Standard time'],['Political use','Empire + state building']],['Industrial cities expanded rapidly.','Telegraph networks increasingly ran beside tracks.','Imperial competition intensified across Africa and Asia.'],['industrial-revolution','steam-engine','world-war-i'],'machine'),
X('world-war-i','world-wars','World War I','1914–1918','Global','Cheshire Regiment trench Somme 1916.jpg','Wikimedia Commons · public-domain UK government image','A European crisis became a world war because rival empires, alliances, mobilization systems, colonial possessions, and global finance linked distant societies to the conflict.',[
['From crisis to general war','The assassination of Archduke Franz Ferdinand triggered an international crisis, but war resulted from political decisions, alliance commitments, military plans, nationalism, and imperial rivalry. Mobilization accelerated escalation.'],
['Industrialized battle','Machine guns, artillery, railways, barbed wire, aircraft, poison gas, and mass armies created enormous killing power. Trench warfare became emblematic on the Western Front, while mobile and brutal campaigns unfolded in Eastern Europe, the Middle East, Africa, and at sea.'],
['Societies at war','States mobilized food, industry, labor, propaganda, and colonial manpower. Civilians endured blockade, occupation, displacement, famine, and mass violence, including the Armenian genocide in the Ottoman Empire.'],
['A shattered order','The war destroyed the German, Austro-Hungarian, Ottoman, and Russian empires. New states emerged, revolution transformed Russia, colonial expectations shifted, and the postwar settlements generated conflicts that would shape the next decades.']],[['28 June 1914','Franz Ferdinand assassinated'],['1916','Verdun and the Somme'],['1917','United States enters; Russian revolutions'],['11 November 1918','Armistice on Western Front']],[['Duration','1914–1918'],['System','Mass mobilization'],['Fronts','Global'],['Aftermath','Four empires collapse']],['Colonial troops and laborers crossed oceans for the war.','The Ottoman Empire fought across several Middle Eastern fronts.','Japan expanded its position in East Asia and the Pacific.'],['world-war-ii','age-of-railroads'],'timeline'),
X('world-war-ii','world-wars','World War II','1939–1945','Global','Into the Jaws of Death (6414569).jpg','Robert F. Sargent / U.S. Coast Guard · public domain','The deadliest conflict in modern history combined mechanized warfare, occupation, genocide, strategic bombing, resistance, and worldwide mobilization.',[
['War expands','Germany invaded Poland in September 1939 after years of Nazi revisionism and aggression. France fell in 1940; Britain remained at war. Germany invaded the Soviet Union in 1941, while Japan’s attack on Pearl Harbor brought the United States fully into the conflict.'],
['A truly global conflict','Fighting stretched from the Atlantic and Arctic to North Africa, China, Southeast Asia, and the Pacific islands. The Soviet–German front consumed enormous forces, while Allied sea power, industrial capacity, and global logistics became decisive.'],
['Occupation and genocide','Nazi Germany built a racial empire based on terror, forced labor, mass shooting, starvation, and deportation. The Holocaust murdered six million Jews; Roma, disabled people, Soviet prisoners, Poles, and many other groups were also persecuted and killed.'],
['Defeat of the Axis','Allied forces invaded Normandy in June 1944 while the Soviet army advanced from the east. Germany surrendered in May 1945. Japan surrendered in August after continued conventional destruction, Soviet entry into the war against Japan, and U.S. atomic bombings of Hiroshima and Nagasaki.']],[['1 September 1939','Germany invades Poland'],['22 June 1941','Operation Barbarossa'],['6 June 1944','D-Day landings'],['May–September 1945','Axis powers defeated']],[['Scale','Global'],['Eastern Front','Central to defeat of Nazi Germany'],['Crime','Holocaust'],['End','1945']],['Anti-colonial politics gained force across Asia and Africa.','The Manhattan Project created the first nuclear weapons.','Computing advanced rapidly under wartime demands.'],['holocaust','cold-war','computing'],'timeline'),
X('holocaust','world-wars','The Holocaust','1933–1945','Europe','Selection on the ramp at Auschwitz-Birkenau, 1944 (Auschwitz Album) 1b.jpg','Auschwitz Album · Wikimedia Commons','The Holocaust was the systematic persecution and murder of six million European Jews by Nazi Germany and its allies and collaborators, embedded within a broader regime of racial persecution and genocidal war.',[
['Exclusion becomes persecution','After taking power in 1933, the Nazi regime stripped Jews of rights, livelihoods, and citizenship while normalizing antisemitic propaganda and violence. Territorial expansion placed millions more Jews under Nazi control.'],
['Mass murder in occupied Europe','Germany’s invasion of the Soviet Union in 1941 was accompanied by mass shootings by Einsatzgruppen, police units, soldiers, and collaborators. Deportation and ghettoization produced starvation, disease, forced labor, and terror.'],
['Killing centers','Nazi authorities created killing centers in occupied Poland, including Auschwitz-Birkenau, Treblinka, Bełżec, Sobibór, Chełmno, and Majdanek. Deportation trains linked communities across Europe to systems of mass murder.'],
['Victims, resistance, memory','Jews resisted in ghettos, camps, forests, households, and underground networks despite extreme conditions. Nazi persecution also targeted Roma and Sinti, disabled people, Poles, Soviet prisoners of war, gay men, political opponents, and others in different ways.']],[['1933','Nazi seizure of power'],['1935','Nuremberg Laws'],['1941','Mass shooting campaigns escalate'],['1942–1944','Deportations to killing centers intensify']],[['Jewish victims','About six million'],['Method','Shooting, starvation, gassing, forced labor'],['Geography','Across occupied Europe'],['Principle','Remember victims as individuals']],['World War II raged across Europe, Africa, and Asia.','Resistance movements operated in occupied countries.','Governments and refugees struggled over rescue, borders, and information.'],['world-war-ii','cold-war'],'archive'),
X('cold-war','modern','The Cold War','c. 1947–1991','Global','Berlin Wall 1961-11-20.jpg','U.S. National Archives · public domain','Rival U.S.- and Soviet-led systems shaped alliances, nuclear strategy, proxy wars, development, espionage, culture, and spaceflight without producing a sustained direct war between the superpowers.',[
['A divided postwar order','Disputes over Europe, Germany, security, ideology, and reconstruction hardened after 1945. NATO and the Warsaw Pact institutionalized military blocs, while the division of Germany and Berlin became recurring flashpoints.'],
['Nuclear danger','The arms race produced thermonuclear weapons, submarines, bombers, missiles, early-warning systems, and doctrines of deterrence. The Cuban Missile Crisis of 1962 brought the superpowers dangerously close to nuclear war.'],
['Proxy wars and decolonization','Korea, Vietnam, Afghanistan, and many other conflicts were shaped by Cold War intervention, but local actors had their own goals. Newly independent states often rejected the idea that they simply belonged to one of two camps.'],
['Competition and collapse','Scientific prestige, sport, media, intelligence, aid, and the Space Race became arenas of competition. Soviet reforms, economic problems, nationalist movements, and political upheaval culminated in the collapse of communist governments in Eastern Europe and dissolution of the USSR.']],[['1947','Truman Doctrine and intensifying rivalry'],['1961','Berlin Wall built'],['1962','Cuban Missile Crisis'],['1991','Soviet Union dissolves']],[['Blocs','U.S. & Soviet-led'],['Central danger','Nuclear war'],['Global dimension','Proxy conflicts'],['End point','1991']],['Decolonization created dozens of new states.','The Space Race accelerated rocket and computing programs.','Civil rights and social movements challenged existing political orders.'],['decolonization','collapse-soviet-union','apollo-11'],'timeline'),
X('decolonization','modern','Decolonization','c. 1945–1970s','Africa, Asia & beyond','Colonial Africa 1913 map.svg','Eric Gaba · Wikimedia Commons · CC BY-SA','After World War II, anticolonial movements dismantled most European overseas empires, but independence came through very different paths—from negotiation and mass politics to protracted war.',[
['Empires under pressure','Colonial powers emerged from World War II economically strained and faced stronger nationalist movements, labor activism, veterans, international anti-imperial arguments, and changing calculations about the costs of rule.'],
['Many roads to sovereignty','India and Pakistan became independent in 1947 amid partition and mass violence. Indonesia fought Dutch attempts to restore rule. Algeria won independence after a brutal war. Across Africa, transfers of power varied widely in timing and conflict.'],
['Independence was a beginning','New states inherited borders, unequal economies, administrative structures, and Cold War pressures. Leaders pursued nonalignment, socialism, capitalism, pan-Africanism, and other projects while confronting coups, debt, regional conflict, and continuing foreign influence.']],[['1947','India and Pakistan become independent'],['1949','Indonesian sovereignty recognized by the Netherlands'],['1957','Ghana gains independence'],['1960','“Year of Africa” brings many independences']],[['Core issue','Political sovereignty'],['Not one process','Negotiation + war'],['Global setting','Cold War'],['Continuity','Colonial economic legacies']],['The United Nations became a major diplomatic arena.','U.S.–Soviet rivalry entered newly independent states.','Pan-African and nonaligned movements built transnational networks.'],['cold-war','age-of-exploration'],'map'),
X('collapse-soviet-union','modern','The Collapse of the Soviet Union','1985–1991','USSR & Eastern Europe','Bundesarchiv Bild 183-1989-1109-030, Berlin, Schabowski auf Pressekonferenz.jpg','Bundesarchiv / Thomas Lehmann · CC BY-SA 3.0','The Soviet Union’s dissolution emerged from interacting economic stagnation, political reform, nationalist movements, institutional conflict, and the rapid unraveling of communist rule across Eastern Europe.',[
['Reform opens politics','Mikhail Gorbachev’s perestroika and glasnost sought to revitalize the Soviet system but widened public debate and reduced the state’s ability to contain criticism. Economic reform produced mixed and often destabilizing results.'],
['Eastern Europe changes','In 1989, communist governments fell across Eastern Europe. The opening of the Berlin Wall became a symbol of the transformation, but changes followed distinct national movements, negotiations, protests, and political crises.'],
['Republics claim sovereignty','National movements strengthened in the Baltic republics, Caucasus, Ukraine, Russia, and elsewhere. After the failed August 1991 coup against Gorbachev, republican leaders rapidly accumulated power.'],
['December 1991','Leaders of Russia, Ukraine, and Belarus declared the Soviet Union effectively ended and formed the Commonwealth of Independent States. Gorbachev resigned on 25 December, and the USSR formally ceased to exist.']],[['1985','Gorbachev becomes general secretary'],['1989','Eastern European communist governments fall'],['August 1991','Failed hard-line coup'],['December 1991','Soviet Union dissolves']],[['Reform','Perestroika + glasnost'],['Symbol','Berlin Wall opening'],['Structure','15 union republics'],['End','December 1991']],['The World Wide Web was emerging.','European integration accelerated.','Post-Cold War conflicts and new states reshaped Eurasia.'],['cold-war','computing'],'timeline'),
X('computing','science','The History of Computing','19th century–present','Global','Eniac (cropped).jpg','U.S. Army · Wikimedia Commons · public domain','Computing grew from centuries of calculation, logic, automation, telecommunications, wartime engineering, semiconductor physics, software, networking, and mass manufacturing.',[
['Before electronic computers','Mechanical calculators, punched-card systems, Boolean logic, and Charles Babbage’s unrealized engines established important ideas about automated calculation. Ada Lovelace famously described how a general machine might manipulate symbols, not just numbers.'],
['Electronic machines','World War II accelerated electronic computing. Machines such as Colossus, ENIAC, and stored-program successors approached computing through different architectures and purposes. No single machine can cleanly be called the only “first computer.”'],
['From transistor to personal computer','The transistor replaced bulky vacuum tubes in many applications; integrated circuits placed multiple electronic components on chips. Falling cost and rising reliability enabled minicomputers, personal computers, and embedded systems.'],
['Networks to AI','ARPANET, packet switching, the internet, and the World Wide Web connected machines and information. Smartphones and cloud systems placed networked computation almost everywhere; machine-learning systems later expanded what computers could infer and generate from data.']],[['1830s','Babbage designs Analytical Engine'],['1945–1946','ENIAC completed and unveiled'],['1947','Transistor demonstrated'],['1969 onward','ARPANET and networked computing expand']],[['Early concept','Programmability'],['Key hardware','Transistor + integrated circuit'],['Network','Internet'],['Current frontier','Artificial intelligence']],['World War II accelerated codebreaking and electronics.','Cold War military funding supported computing and networking.','Spaceflight demanded compact, reliable guidance computers.'],['printing-press','apollo-11','cold-war'],'machine'),
X('printing-press','science','The Printing Press','c. 1450 onward','Europe → world','Press1520.png','Wikimedia Commons · public domain','Movable-type printing in fifteenth-century Europe dramatically lowered the cost of reproducing many kinds of texts, accelerating circulation without creating mass literacy overnight.',[
['A technology with precedents','Woodblock printing had long histories in East Asia, and movable type was developed in China and Korea centuries before Gutenberg. In Europe, alphabetic type, metalworking, oil-based inks, paper, and screw presses combined in a commercially powerful system.'],
['Gutenberg and workshops','Johannes Gutenberg’s mid-fifteenth-century work in Mainz is associated with durable metal movable type and high-quality book production. Printing quickly spread through networks of skilled workers, investors, merchants, universities, and cities.'],
['Information moves faster','Printed books, pamphlets, diagrams, maps, religious arguments, scientific observations, and political polemic circulated widely. Print supported the Reformation and scientific exchange while states and churches responded with licensing and censorship.']],[['c. 1040','Bi Sheng associated with movable type in China'],['13th century','Metal movable type used in Korea'],['c. 1450','Gutenberg’s European press system'],['16th century','Printing becomes central to European religious and scholarly conflict']],[['Earlier tradition','East Asian printing'],['European center','Mainz'],['Material','Metal type + paper + ink'],['Effect','Faster reproduction']],['Renaissance humanism expanded textual scholarship.','Ottoman, Safavid, and Mughal states developed large manuscript and book cultures.','Oceanic exploration increased demand for maps and reports.'],['renaissance','computing'],'machine'),
X('steam-engine','science','The Steam Engine','17th–19th centuries','Britain & beyond','Watt steam pumping engine.JPG','Wikimedia Commons · public-domain historical diagram','Steam engines converted heat into mechanical work and became a central technology of industrialization, but they emerged through repeated improvement rather than a single moment of invention.',[
['Pumping water','Early practical atmospheric engines such as Thomas Newcomen’s were used to pump water from mines. They consumed large amounts of fuel but solved an important industrial problem.'],
['Watt’s improvements','James Watt’s separate condenser greatly improved efficiency. Partnerships, precision manufacturing, patents, and new rotary mechanisms expanded steam power beyond pumping into factories.'],
['Transport and fossil energy','High-pressure engines later powered locomotives and steamships. Steam tied industrial growth more tightly to coal, enabling extraordinary output while helping launch the fossil-fuel energy system behind modern climate change.']],[['1712','Newcomen atmospheric engine demonstrated'],['1760s','Watt develops separate condenser'],['1780s','Rotary Watt engines enter factories'],['19th century','Steam powers rail and ocean transport']],[['Fuel','Coal'],['Transformation','Heat → work'],['Key improvement','Separate condenser'],['Legacy','Industrial fossil-energy system']],['Coal mining expanded dramatically.','Mechanized textiles raised demand for reliable power.','Canals and later railways restructured transport.'],['industrial-revolution','age-of-railroads'],'machine'),
X('apollo-11','space','Apollo 11 & the Space Race','16–24 July 1969','Earth ↔ Moon','AS11-40-5903 - Buzz Aldrin by Neil Armstrong (full frame).jpg','Neil Armstrong / NASA · public domain','Apollo 11 put humans on another world, but the landing was the culmination of decades of rocketry, Cold War competition, industrial organization, test flights, computing, and human risk.',[
['From Sputnik to Apollo','The Soviet launch of Sputnik in 1957 and Yuri Gagarin’s 1961 orbital flight shocked the United States. President John F. Kennedy then committed the nation to a crewed lunar landing before the decade ended.'],
['Mercury, Gemini, Saturn V','Mercury tested basic human spaceflight. Gemini developed rendezvous, docking, long-duration flight, and spacewalk experience. The enormous Saturn V and Apollo spacecraft integrated propulsion, navigation, communications, life support, and thousands of contractors.'],
['The landing','Apollo 11 launched on 16 July 1969. Neil Armstrong and Buzz Aldrin landed Eagle in Mare Tranquillitatis on 20 July while Michael Collins remained in lunar orbit aboard Columbia. The crew returned safely on 24 July.'],
['Science and geopolitics','The mission collected lunar samples and deployed experiments, but its funding and urgency were inseparable from superpower rivalry. Apollo became both an engineering achievement and a symbol carefully interpreted around the world.']],[['1957','Sputnik 1'],['1961','Yuri Gagarin orbits Earth'],['1965–1966','Gemini develops rendezvous and docking'],['20 July 1969','Apollo 11 lunar landing']],[['Crew','Armstrong · Aldrin · Collins'],['Rocket','Saturn V'],['Landing site','Mare Tranquillitatis'],['Return','24 July 1969']],['The Vietnam War continued.','ARPANET connected its first nodes later in 1969.','The Soviet Union continued its own lunar and robotic space programs.'],['cold-war','computing','voyager'],'mission'),
X('voyager','space','The Voyager Program','1977–present','Outer Solar System','Voyager spacecraft.jpg','NASA/JPL · public domain','Voyager 1 and Voyager 2 used a rare planetary alignment to transform knowledge of the giant planets, then continued outward to explore the boundary between the heliosphere and interstellar space.',[
['The Grand Tour opportunity','A favorable alignment allowed a spacecraft to use gravity assists from one giant planet to reach the next. Voyager 2 ultimately visited Jupiter, Saturn, Uranus, and Neptune; Voyager 1 followed a different path after Saturn.'],
['New worlds in detail','The missions revealed active volcanism on Io, complex ring systems, new moons, atmospheric structures, and surprising surfaces. Voyager 2 remains the only spacecraft to have visited Uranus and Neptune.'],
['Beyond the planets','Voyager 1 and later Voyager 2 crossed the heliopause into interstellar space. Their instruments continue to study particles, magnetic fields, and plasma far from the Sun, while power declines as their radioisotope generators age.']],[['1977','Voyager 1 and 2 launch'],['1979','Jupiter encounters'],['1986','Voyager 2 reaches Uranus'],['1989','Voyager 2 reaches Neptune']],[['Spacecraft','Voyager 1 + 2'],['Power','Radioisotope generators'],['Unique first','Uranus + Neptune flybys'],['Long mission','Interstellar measurements']],['The Cold War still shaped space budgets.','Personal computing was beginning to spread.','Robotic planetary exploration was becoming a major branch of space science.'],['apollo-11','iss'],'mission'),
X('iss','space','The International Space Station','1998–present','Low Earth orbit','International Space Station after undocking of STS-132.jpg','NASA · public domain','The International Space Station is both a large orbital laboratory and a political project: a continuously inhabited infrastructure built, supplied, repaired, and operated by an international partnership.',[
['Assembly in orbit','The first ISS module launched in 1998. Subsequent modules, trusses, solar arrays, laboratories, docking systems, and living spaces were assembled through many missions rather than launched as one object.'],
['Living laboratory','Crews conduct experiments in microgravity across biology, medicine, materials, fluids, combustion, Earth observation, and technology demonstrations. Long-duration missions also study how the human body adapts to space.'],
['International system','The partnership has involved the United States, Russia, Europe, Japan, Canada, and others through complex agreements and hardware dependencies. The station shows both the possibilities and limits of sustained cooperation in space.']],[['1998','First module, Zarya, launched'],['2000','Continuous human occupation begins'],['2011','Major assembly era largely complete'],['present','Research and commercial activity continue']],[['Orbit','Low Earth orbit'],['Occupation','Continuous since 2000'],['Function','Microgravity laboratory'],['Structure','International partnership']],['Global internet infrastructure expanded rapidly.','Robotic spacecraft explored Mars and the outer Solar System.','Commercial launch companies began taking larger roles in orbital transportation.'],['apollo-11','voyager'],'mission')
],timeline:[
[-10000,'Early farming experiments','Southwest Asia and other regions','neolithic-revolution'],[-3500,'Cities grow in Mesopotamia','Tigris–Euphrates','mesopotamia'],[-3100,'Egyptian state formation','Nile Valley','ancient-egypt'],[-1200,'Eastern Mediterranean crisis','Eastern Mediterranean','bronze-age-collapse'],[-550,'Achaemenid Persian expansion','West Asia','persian-empire'],[-334,'Alexander crosses into Asia','Mediterranean & Asia','alexander-the-great'],[-206,'Han dynasty begins','East Asia','han-china'],[-27,'Augustus and imperial Rome','Mediterranean','roman-empire'],[537,'Hagia Sophia completed','Constantinople','byzantine-empire'],[1206,'Chinggis Khan proclaimed','Mongolian steppe','mongol-empire'],[1347,'Black Death reaches Mediterranean ports','Eurasia','black-death'],[1450,'European movable-type printing expands','Europe','printing-press'],[1492,'Sustained Atlantic contact accelerates','Atlantic','age-of-exploration'],[1769,'Watt patents major steam-engine improvement','Britain','steam-engine'],[1825,'Early public steam railway','Britain','age-of-railroads'],[1914,'World War I begins','Global','world-war-i'],[1939,'World War II begins in Europe','Global','world-war-ii'],[1945,'War ends; new international order','Global','world-war-ii'],[1947,'Cold War rivalry hardens','Global','cold-war'],[1957,'Sputnik launches','Space','apollo-11'],[1960,'Many African states gain independence','Africa','decolonization'],[1969,'Humans land on the Moon','Moon','apollo-11'],[1977,'Voyager spacecraft launch','Outer Solar System','voyager'],[1989,'Berlin Wall opens','Europe','collapse-soviet-union'],[1991,'Soviet Union dissolves','Eurasia','collapse-soviet-union'],[1998,'ISS assembly begins','Low Earth orbit','iss'],[2000,'Continuous ISS occupation begins','Low Earth orbit','iss']
]};